# ===== PROD Profile - PostgreSQL Database =====

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=ticketcodedb


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# H2 Console disabled in prod
spring.h2.console.enabled=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.TicketCodeIA=INFO
logging.level.org.springframework.ai=WARN
