package TicketCodeIA.domain.model.agent;

import TicketCodeIA.domain.enums.AgentType;
import TicketCodeIA.domain.enums.Priority;
import TicketCodeIA.domain.model.ticket.Ticket;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Domain aggregate representing the Product Owner agent.
 * Responsible for breaking down requirements into well-formed tickets.
 * Unlike other agents, the PO does not process existing tickets through the pipeline
 * but instead creates new tickets from raw requirements.
 */
public class POAgent {

    private final AgentType type = AgentType.PO;

    public AgentType getType() {
        return type;
    }

    /**
     * Creates domain Ticket objects from raw ticket data generated by AI.
     * Validates and normalizes the data (priority parsing, defaults).
     */
    public List<Ticket> createTicketsFromData(List<Map<String, String>> ticketDataList,
                                               Long projectId, String projectName) {
        List<Ticket> tickets = new ArrayList<>();
        for (Map<String, String> data : ticketDataList) {
            String title = data.getOrDefault("title", "Untitled");
            String description = data.getOrDefault("description", "");
            Priority priority = parsePriority(data.get("priority"));
            boolean enableCodeReview = parseBoolean(data.get("enableCodeReview"), false);
            boolean enableTesting = parseBoolean(data.get("enableTesting"), false);
            Ticket ticket = Ticket.create(title, description, priority, projectId, projectName);
            ticket.setEnableCodeReview(enableCodeReview);
            ticket.setEnableTesting(enableTesting);
            tickets.add(ticket);
        }
        return tickets;
    }

    private boolean parseBoolean(String value, boolean defaultValue) {
        if (value == null || value.isBlank()) return defaultValue;
        return "true".equalsIgnoreCase(value.trim());
    }

    private Priority parsePriority(String priorityStr) {
        if (priorityStr == null || priorityStr.isBlank()) {
            return Priority.MEDIUM;
        }
        try {
            return Priority.valueOf(priorityStr.toUpperCase().trim());
        } catch (IllegalArgumentException e) {
            return Priority.MEDIUM;
        }
    }
}
